<?php
// by github.com/Prospection 2014
// $Id: sms_registration.module

/**
 * Implementation of hook_menu().
 */

function sms_registration_phone_validate($phone)
{
    //not used for now
    return true;
}

function sms_registration_make_mail($phone)
{
    $phone = str_replace(array('+', '-', ' ', '(', ')'), '', $phone);
    return intval($phone) . '@cekatop.ru';
}

function sms_registration_make_username($phone)
{
    $phone = str_replace(array('+', '-', ' '), '', $phone);
    $phone = intval($phone);
    return $phone;
}

function sms_registration_make_pass()
{
    $characters = '0123456789';
    $randomString = '';
    $length = 5;
    for ($i = 0; $i < $length; $i++) {
        $randomString .= $characters[rand(0, strlen($characters) - 1)];
    }
    return $randomString;
}

function sms_registration_form_alter(&$form, &$form_state, $form_id)
{
    if ($form_id == 'uc_cart_checkout_form') {
        $form['panes']['customer']['primary_email']['#required'] = false;
        $form['panes']['customer']['sms_registration_phone'] = array(
            '#type' => 'textfield',
            '#title' => t('OR only Phone number'),
            '#description' => t('You will receive a message with password.'),
            '#size' => 40,
            '#maxlength' => 255,
            '#required' => false,
        );
    }
    if ($form_id == 'user_pass') {
        $form['name']['#title'] = t('Электронная почта, логин, телефон');
        array_unshift($form['#validate'], 'sms_registration_forget_validate');
    }
    if ($form_id == 'user_login') {
        $form['name']['#title'] = t('Логин');
    }
    // we have some custom form on site, feel free to comment next lines
    if ($form_id == 'user_login_1') {
        $form['name']['#title'] = t('Логин');
    }
}

function sms_registration_forget_validate(&$form, &$form_state)
{
    $phone = sms_registration_make_username($form_state['values']['name']);
    if (db_result(db_query("SELECT COUNT(*) FROM {users} WHERE name = '%s';", $phone))) {
        $p = sms_registration_make_pass();
        sms_registration_send($phone, t('Ваш логин') . ' . $phone . ', t('пароль'). $p, $options);
        $p = md5($p);
        db_query("UPDATE {users} SET pass ='%s'  WHERE name = '%s'", $p, $phone);
        drupal_set_message(t('Вам отправлена SMS на телефон: ') . $phone);
    }
    return true;
}

function sms_registration_checkout_pane()
{
    $panes[] = array(
        'id' => 'customer',
        'callback' => 'sms_registration_make_checkout',
        'title' => t('Customer information'),
        'desc' => t('Get the necessary information to create a customer on the site.'),
        'weight' => 2,
    );
    return $panes;
}

function sms_registration_make_checkout($op, &$arg1, $arg2)
{
    global $user;
    switch ($op) {
        case 'view':
            return;
        case 'process':
            if ($arg2['primary_email']) $arg1->primary_email = $arg2['primary_email'];
            $phone = $arg1->delivery_phone;
            if ($phone) {
                $phone = $arg1->delivery_phone = str_replace(array('+', '-', ' ', '(', ')'), '', $phone);
            }
            if (empty($arg2['primary_email']) && $phone) { //check if only phone
                $no_email = true;
                if (!empty($phone) && !sms_registration_phone_validate($phone)) {
                    form_set_error('panes][customer][sms_registration_phone', t('You must enter a valid phone.'));
                }
                if (!empty($phone) && sms_registration_phone_validate($phone)) {
                    if (isset($user->mail)) {
                        $email = $user->mail;
                    } else {
                        $e = sms_registration_make_mail($phone);
                        $email = $e;
                        $arg1->primary_email = $e;
                    }
                }
            } //done with phone

            if ($no_email && $user->uid == 0 &&
                $a = db_result(db_query("SELECT uid FROM {users} WHERE name = '%s';", $phone))
            ) {
            }
            // If new users can specify names or passwords then...
            if ($user->uid == 0
                && !db_result(db_query("SELECT COUNT(*) FROM {users} WHERE name = '%s';", $phone))
                && $no_email
            ) {
                // Skip if an account already exists for this e-mail address.
                if (!$arg1->data['new_user']['pass']) {
                    $n = sms_registration_make_username($phone);
                    $arg1->data['new_user']['name'] = $n;
                    $p = sms_registration_make_pass();
                    $arg1->data['new_user']['pass'] = $p;
                    $arg1->data['new_user']['hash'] = md5(trim($p));
                    $arg1->password = $p; //shows on order complete
                }
            }
            return TRUE;
        case
        'review':
            break;
    }
}

function sms_registration_uc_checkout_complete($order, $account)
{
    if($order->password) $order->data['new_user']['pass']=$order->password;
    if ($order->delivery_ucxf_sms) {
        if (is_array($order->data['new_user'])) {
            $o = t('Ваш заказ:'). $order->information_ucxf_order_num . " ".t('принят!');
            $o .= "\n" . t('Ваш логин:') . $order->data['new_user']['name'] . ', '.t('пароль').': ' . $order->data['new_user']['pass'];
            sms_registration_send($order->delivery_phone, $o, $options);
        } else {
            $o = t('Ваш заказ:') . $order->information_ucxf_order_num . " ".t('принят!');
            sms_registration_send($order->delivery_phone, $o, $options);
        }
    }
}

function sms_registration_gateway_info()
{
    return array(
        'mainsms' => array(
            'name' => 'Main SMS',
            'configure form' => 'sms_mainsms_admin_form',
            'receive' => TRUE,
            'send' => 'sms_mainsms_send',
            'send form' => 'sms_mainsms_send_form',
        ),
    );
}

function sms_registration_send($number, $message, $options)
{
    return sms_registration_command('sendmsg', array('number' => $number, 'message' => $message), NULL, NULL);
}

function sms_registration_command($command = 'auth', $data = array(), $config = NULL, $account = '')
{
    if ($config == NULL) {
        $config['sms_mainsms_project'] = 'XXXXX'; // put data credentials from sms.ru
        $config['sms_mainsms_api_key'] = 'XXXX';
        $config['sms_mainsms_sender'] = 'XXXX';
    }
    switch ($command) {
        case 'sendmsg':
            $data['message'] = urlencode($data['message']);
            $query = 'http://sms.ru/sms/send?api_id=' . $config['sms_mainsms_api_key'] . '&to="' . $data['number'] . '"' . $config['sms_mainsms_sender'] . '&text=' . $data['message'];
            $result = @file_get_contents($query);
            return $result;
    }

}
